<?php
declare(strict_types=1);

namespace {
	define('ABSPATH',__DIR__.'/');define('MINUTE_IN_SECONDS',60);define('AG_SYNC_BRIDGE_V4MPG_ALLOWED_TARGETS','6:italia-6,9:italia-9');
	$GLOBALS['v4mpg_transients']=array();
	$GLOBALS['v4mpg_barrier_events']=array();
	function __($v){return $v;} function home_url(){return 'https://live.example';} function wp_generate_uuid4(){return '12345678-1234-1234-1234-123456789012';}
	function sanitize_text_field($v){return trim((string)$v);} function get_transient($k){return $GLOBALS['v4mpg_transients'][$k]??false;} function set_transient($k,$v,$ttl){$GLOBALS['v4mpg_transients'][$k]=$v;return true;} function is_wp_error($v){return $v instanceof WP_Error;}
	function wp_json_encode($v,$flags=0){return json_encode($v,$flags|JSON_THROW_ON_ERROR);} function wp_parse_url($url,$component=-1){return parse_url($url,$component);} function untrailingslashit($v){return rtrim($v,'/');}
	function di_cache_epoch_barrier_begin(string $operation_id): ?array{$GLOBALS['v4mpg_barrier_events'][]='begin:'.$operation_id;return array('operation_id'=>$operation_id,'epoch'=>'epoch-1');}
	function di_cache_epoch_barrier_bump(array &$token,string $reason='barrier-switch'): ?string{$GLOBALS['v4mpg_barrier_events'][]='bump:'.$reason;$token['epoch']='epoch-2';return 'epoch-2';}
	function di_cache_epoch_barrier_end(array $token): bool{$GLOBALS['v4mpg_barrier_events'][]='end:'.$token['operation_id'];return true;}
	class WP_Error{private $code;private $message;public function __construct($c='',$m=''){ $this->code=$c;$this->message=$m;}public function get_error_code(){return $this->code;}public function get_error_message(){return $this->message;}}
	class WP_REST_Request{private $method,$route,$headers,$body;public function __construct($m,$r,$h,$b){$this->method=$m;$this->route=$r;$this->headers=array_change_key_case($h,CASE_LOWER);$this->body=$b;}public function get_header($n){return $this->headers[strtolower($n)]??'';}public function get_route(){return $this->route;}public function get_method(){return $this->method;}public function get_body(){return $this->body;}}
}

namespace AGSyncBridge {
	class Config{public function get_secret(){return 'v4mpg-secret';}public function set_state_value($k,$v){}}
	class Logger{}
	require_once dirname(__DIR__).'/includes/class-auth.php';
	require_once dirname(__DIR__).'/includes/class-v4mpg-table-deploy-service.php';
	function expect_v4($condition,$message){if(!$condition){throw new \RuntimeException($message);}}
	function expect_throw(callable $call,$contains){try{$call();}catch(\Throwable $e){expect_v4(false!==strpos($e->getMessage(),$contains),'Unexpected error: '.$e->getMessage());return;}throw new \RuntimeException('Expected failure: '.$contains);}

	$auth=new Auth(new Config(),new Logger());
	foreach(array('plan','backup','backup-page','backup-seal','backup-abort','deploy','verify','rollback','status','recover') as $action){$route='/ag-sync-bridge/v1/v4mpg-table/'.$action;$body='{"protocol":1}';$headers=$auth->build_headers('POST',$route,$body);expect_v4(true===$auth->verify_rest_request(new \WP_REST_Request('POST',$route,$headers,$body)),'Signed V4MPG route rejected: '.$action);$unsigned=$headers;unset($unsigned['X-AGSB-Nonce']);$rejected=$auth->verify_rest_request(new \WP_REST_Request('POST',$route,$unsigned,$body));expect_v4(is_wp_error($rejected)&&'ag_sync_bridge_body_signature_required'===$rejected->get_error_code(),'Legacy downgrade accepted: '.$action);}

	$reflection=new \ReflectionClass(V4MPG_Table_Deploy_Service::class);$service=$reflection->newInstanceWithoutConstructor();$validator=$reflection->getMethod('validate_candidate');$validator->setAccessible(true);
	$state_file=$reflection->getProperty('state_file');$state_file->setAccessible(true);$journal=sys_get_temp_dir().'/agsb-v4-corrupt-'.bin2hex(random_bytes(4)).'.json';file_put_contents($journal,'{broken');$state_file->setValue($service,$journal);$read_state=$reflection->getMethod('read_state');$read_state->setAccessible(true);expect_throw(static function()use($read_state,$service){$read_state->invoke($service);},'corrupt');unlink($journal);
	$begin_barrier=$reflection->getMethod('begin_cache_epoch_barrier');$begin_barrier->setAccessible(true);$advance_barrier=$reflection->getMethod('advance_cache_epoch_barrier');$advance_barrier->setAccessible(true);$end_barrier=$reflection->getMethod('end_cache_epoch_barrier');$end_barrier->setAccessible(true);$token=$begin_barrier->invoke($service,'operation-1234');$advance_args=array(&$token,'after-commit');$advance_barrier->invokeArgs($service,$advance_args);$end_barrier->invoke($service,$token);expect_v4(array('begin:operation-1234','bump:after-commit','end:operation-1234')===$GLOBALS['v4mpg_barrier_events'],'Exclusive cache barrier begin/bump/end contract was not followed.');
	$ambiguous=$reflection->getMethod('is_ambiguous_state');$ambiguous->setAccessible(true);foreach(array('prepared-to-commit','committed-needs-postverify','rollback_required','rollback-prepared-to-commit','rollback-committed-needs-verify','deployed-needs-barrier-release','deployed-needs-runtime-finalize','rolled-back-needs-barrier-release','rolled-back-needs-runtime-finalize','recovery-verified-needs-barrier-release','recovery-verified-needs-runtime-finalize') as $state){expect_v4(true===$ambiguous->invoke($service,$state),'Recovery quarantine does not cover '.$state);}expect_v4(false===$ambiguous->invoke($service,'deployed'),'Terminal deployed state was classified as ambiguous.');
	$classify=$reflection->getMethod('classify_recovery_evidence');$classify->setAccessible(true);$receipt_datasets=array(array('project_id'=>1,'dataset_id'=>'a','previous_version_id'=>10,'previous_dataset_sha256'=>str_repeat('1',64),'previous_urls_sha256'=>str_repeat('2',64),'previous_row_count'=>100,'new_version_id'=>11,'new_version_key'=>'new-a','new_dataset_sha256'=>str_repeat('3',64),'new_urls_sha256'=>str_repeat('2',64),'new_row_count'=>100),array('project_id'=>2,'dataset_id'=>'b','previous_version_id'=>20,'previous_dataset_sha256'=>str_repeat('4',64),'previous_urls_sha256'=>str_repeat('5',64),'previous_row_count'=>200,'new_version_id'=>21,'new_version_key'=>'new-b','new_dataset_sha256'=>str_repeat('6',64),'new_urls_sha256'=>str_repeat('5',64),'new_row_count'=>200));$old_evidence=array(array('project_id'=>1,'dataset_id'=>'a','active_version_id'=>10,'version_key'=>'old-a','dataset_sha256'=>str_repeat('1',64),'urls_sha256'=>str_repeat('2',64),'row_count'=>100),array('project_id'=>2,'dataset_id'=>'b','active_version_id'=>20,'version_key'=>'old-b','dataset_sha256'=>str_repeat('4',64),'urls_sha256'=>str_repeat('5',64),'row_count'=>200));$new_evidence=array(array('project_id'=>1,'dataset_id'=>'a','active_version_id'=>11,'version_key'=>'new-a','dataset_sha256'=>str_repeat('3',64),'urls_sha256'=>str_repeat('2',64),'row_count'=>100),array('project_id'=>2,'dataset_id'=>'b','active_version_id'=>21,'version_key'=>'new-b','dataset_sha256'=>str_repeat('6',64),'urls_sha256'=>str_repeat('5',64),'row_count'=>200));expect_v4('rolled-back'===$classify->invoke($service,$receipt_datasets,$old_evidence),'Pre-COMMIT fault evidence was not classified as rolled back.');expect_v4('deployed'===$classify->invoke($service,$receipt_datasets,$new_evidence),'Post-COMMIT fault evidence was not classified as deployed.');$mixed=$new_evidence;$mixed[1]=$old_evidence[1];expect_throw(static function()use($classify,$service,$receipt_datasets,$mixed){$classify->invoke($service,$receipt_datasets,$mixed);},'mixed');$tampered=$new_evidence;$tampered[0]['version_key']='wrong';expect_throw(static function()use($classify,$service,$receipt_datasets,$tampered){$classify->invoke($service,$receipt_datasets,$tampered);},'outside');
	$hash=str_repeat('a',64);$after='Testo umano aggiornato';$candidate=array('source_sha256'=>$hash,'dataset_sha256'=>str_repeat('b',64),'header_sha256'=>str_repeat('c',64),'urls_sha256'=>str_repeat('d',64),'row_count'=>7894,'column_count'=>40,'ordered_digest'=>str_repeat('b',64),'changed_cell_count'=>1,'declared_changes'=>array(array('geo_id'=>'006003','field'=>'meta_title','before_hash'=>str_repeat('e',64),'after_hash'=>hash('sha256',"v4mpg-content-v1\0text\0".$after),'after'=>$after)));
	$validated=$validator->invoke($service,$candidate,9,'italia-9');expect_v4(7894===$validated['row_count']&&1===$validated['changed_cell_count'],'Delta candidate did not accept a 7,894-row metadata release.');expect_v4(strlen(V4MPG_Table_Deploy_Service::canonical_json($candidate))<V4MPG_Table_Deploy_Service::MAX_BODY_BYTES,'Delta candidate unexpectedly exceeds body limit.');
	$binding_release=array('release_id'=>'binding-release');$binding_site=array('home_url'=>'https://live.example','site_url'=>'https://live.example','home_host'=>'live.example');$binding_request=array('operation_id'=>'binding-operation','payload_sha256'=>str_repeat('1',64),'backup_sha256'=>str_repeat('2',64),'expected_site'=>$binding_site,'deployment'=>array('release'=>$binding_release));$binding_result=array('status'=>'deployed','operation_id'=>'binding-operation','payload_sha256'=>str_repeat('1',64),'backup_sha256'=>str_repeat('2',64),'site'=>$binding_site,'release'=>$binding_release,'release_sha256'=>V4MPG_Table_Deploy_Service::sha256($binding_release));$binding_backup=array('sha256'=>str_repeat('2',64));expect_v4(true===V4MPG_Table_Deploy_Service::assert_deploy_response_binding($binding_result,$binding_request,$binding_backup),'Exact deploy response binding was rejected.');$tampered_binding=$binding_result;$tampered_binding['backup_sha256']=str_repeat('3',64);expect_throw(static function()use($tampered_binding,$binding_request,$binding_backup){V4MPG_Table_Deploy_Service::assert_deploy_response_binding($tampered_binding,$binding_request,$binding_backup);},'not bound');
	$measured_payloads=array('italia-900-changes-2-targets'=>394806,'pro-900-changes'=>329055);foreach($measured_payloads as $label=>$bytes){expect_v4($bytes<V4MPG_Table_Deploy_Service::MAX_BODY_BYTES,'Measured '.$label.' payload exceeds the protocol body ceiling.');}
	$full=$candidate;$full['rows']=array();expect_throw(static function()use($validator,$service,$full){$validator->invoke($service,$full,9,'italia-9');},'Unexpected or missing JSON fields');
	$bad_field=$candidate;$bad_field['declared_changes'][0]['field']='url_slug';expect_throw(static function()use($validator,$service,$bad_field){$validator->invoke($service,$bad_field,9,'italia-9');},'invalid');
	$duplicate=$candidate;$duplicate['changed_cell_count']=2;$duplicate['declared_changes'][]=$duplicate['declared_changes'][0];expect_throw(static function()use($validator,$service,$duplicate){$validator->invoke($service,$duplicate,9,'italia-9');},'duplicate');

	$source=file_get_contents(dirname(__DIR__).'/includes/class-v4mpg-table-deploy-service.php');
	expect_v4(false!==strpos($source,'INSERT INTO `{$tables[\'rows\']}`')&&false!==strpos($source,'SELECT %d,project_id,row_index'),'Server-side clone is missing.');
	expect_v4(false!==strpos($source,"status'=>'prepared-to-commit'")&&false!==strpos($source,"status'=>'committed-needs-postverify'"),'Commit WAL states are missing.');
	expect_v4(false!==strpos($source,"'kind'=>'sealed'")&&false!==strpos($source,'backup-page'),'Backup seal/page protocol is missing.');
	expect_v4(false!==strpos($source,'AG_SYNC_BRIDGE_V4MPG_ALLOWED_TARGETS'),'Explicit remote target allowlist is missing.');
	expect_v4(false!==strpos($source,'Remote_Operation_Runtime'),'Shared remote operation control plane is missing.');
	expect_v4(false!==strpos($source,'di_cache_epoch_barrier_begin')&&false!==strpos($source,'di_cache_epoch_barrier_bump')&&false!==strpos($source,'di_cache_epoch_barrier_end'),'Exclusive cache epoch barrier contract is missing.');
	expect_v4(false===strpos($source,'acquire_lock(')&&false===strpos($source,'v4mpg-table-operation.lock'),'Crash-stale private V4MPG lock must not coexist with the shared operation runtime.');
	$prepared_pos=strpos($source,"status'=>'prepared-to-commit'");$commit_pos=strpos($source,'$this->commit_transaction();',$prepared_pos);$committed_pos=strpos($source,"status'=>'committed-needs-postverify'",$commit_pos);expect_v4(false!==$prepared_pos&&false!==$commit_pos&&false!==$committed_pos&&$prepared_pos<$commit_pos&&$commit_pos<$committed_pos,'Deploy WAL does not bracket COMMIT correctly.');
	$deploy_method_pos=strpos($source,'public function deploy');$idempotent_pos=strpos($source,"'deployed' ===",$deploy_method_pos);$backup_transient_pos=strpos($source,"get_transient( 'ag_sync_v4mpg_backup_'",$deploy_method_pos);expect_v4(false!==$idempotent_pos&&false!==$backup_transient_pos&&$idempotent_pos<$backup_transient_pos,'Successful deploy retry must return its exact receipt before requiring the consumed backup transient.');
	$transaction_pos=strpos($source,'private function deploy_transaction');$staging_pos=strpos($source,'insert_candidate(',$transaction_pos);$late_barrier_pos=strpos($source,'begin_cache_epoch_barrier',$transaction_pos);$switch_pos=strpos($source,'switch_pointer(',$late_barrier_pos);expect_v4($staging_pos<$late_barrier_pos&&$late_barrier_pos<$switch_pos,'Deploy barrier must be acquired after staging verification and before pointer switch.');
	expect_v4(false!==strpos($source,'clear_targeted_cache( $receipt[\'datasets\'], false )')&&false!==strpos($source,'clear_targeted_cache( $restored, false )'),'Code under the exclusive barrier must not reacquire the legacy full-page-cache lock.');
	$cli_source=file_get_contents(dirname(__DIR__).'/includes/class-v4mpg-table-cli.php');$deploy_pos=strpos($cli_source,"request('deploy'");$deploy_preflight=strpos($cli_source,'preflight_new_output($output)');expect_v4(false!==$deploy_pos&&false!==$deploy_preflight&&$deploy_preflight<$deploy_pos,'Deploy output preflight must happen before remote mutation.');expect_v4(false!==strpos($cli_source,'delete_remote_snapshot_exact($operation_id,$basename,$sha,$manifest_id,$manifest_sha)'),'Full-local backup exact cleanup must bind operation, archive SHA, manifest id, and manifest SHA.');
	expect_v4(false!==strpos($cli_source,"elseif(''!==\$operation_id){\$cleanup_error=new RuntimeException('Exact remote snapshot cleanup proof was unavailable for the started operation.')"),'Started full-backup operations with incomplete metadata must remain marked REMOTE CLEANUP REQUIRED.');
	expect_v4(false!==strpos($cli_source,'assert_no_unresolved_remote_cleanup()')&&false!==strpos($cli_source,"preg_match('/\\.(?:remote|operation)-pending\\.json$/'"),'Deploy must scan the local backup root for unresolved remote cleanup journals.');

	echo "v4mpg table deploy security: ok\n";
}
