<?php
namespace AGSyncBridge;

use RuntimeException;

if ( ! defined( 'ABSPATH' ) ) { exit; }

if ( defined( 'WP_CLI' ) && WP_CLI ) {
	class V4MPG_Table_CLI extends \WP_CLI_Command {
		/** @var V4MPG_Table_Client */ private static $client;
		private static $http; private static $importer; private static $file_system; private static $config;

		public static function register( Config $config, Logger $logger, Auth $auth, Http_Client $http, Import_Service $importer, File_System_Service $file_system ) {
			self::$client = new V4MPG_Table_Client( $config, $auth );
			self::$http=$http;self::$importer=$importer;self::$file_system=$file_system;self::$config=$config;
			\WP_CLI::add_command( 'agsync v4mpg', __CLASS__ );
		}

		/** Read-only remote plan from an exact JSON request. */
		public function plan( $args, $assoc ) { $this->simple( 'plan', $assoc ); }

		/**
		 * Download every scoped backup row to a local file and seal the remote
		 * deploy token only after atomic local persistence and re-read hashing.
		 *
		 * ## OPTIONS
		 * --request=<json-file>
		 * --output=<local-json-file>
		 */
		public function backup( $args, $assoc ) {
			unset($args);$request=$this->read_json_arg($assoc,'request');$output=$this->absolute_output($assoc,'output');
			$open=null;$sealed_ok=false;$handle=null;$partial=$output.'.partial';$open=self::$client->request('backup',$request);
			try{
				$manifest=$open['artifact']??null;if(!is_array($manifest)||!isset($open['backup_token'])||!hash_equals((string)$open['backup_manifest_sha256'],V4MPG_Table_Deploy_Service::sha256($manifest))){throw new RuntimeException('Remote scoped backup manifest verification failed.');}
				if(file_exists($partial)||file_exists($output)){throw new RuntimeException('Backup destination already exists.');}$dir=dirname($output);if(!is_dir($dir)&&!wp_mkdir_p($dir)){throw new RuntimeException('Unable to create local backup directory.');}$handle=fopen($partial,'x+b');if(false===$handle){throw new RuntimeException('Unable to create local partial backup.');}$proofs=array();
				$this->write_exact($handle,V4MPG_Table_Deploy_Service::canonical_json(array('record'=>'manifest','manifest_sha256'=>$open['backup_manifest_sha256'],'manifest'=>$manifest))."\n");
				foreach($manifest['datasets'] as $dataset){$project_id=(int)$dataset['project']['project_id'];$dataset_id=(string)$dataset['version']['dataset_id'];$row_count=(int)$dataset['version']['row_count'];$digest=hash_init('sha256');$page_hashes=array();$seen=0;
					for($offset=0;$offset<$row_count;$offset+=100){$page_response=self::$client->request('backup-page',array('protocol'=>V4MPG_Table_Deploy_Service::PROTOCOL_VERSION,'operation_id'=>$request['operation_id'],'expected_site'=>$request['expected_site'],'backup_token'=>$open['backup_token'],'project_id'=>$project_id,'dataset_id'=>$dataset_id,'offset'=>$offset,'limit'=>100));$page=$page_response['page']??null;if(!is_array($page)||!hash_equals((string)$page_response['page_sha256'],V4MPG_Table_Deploy_Service::sha256($page))||(int)$page['project_id']!==$project_id||(string)$page['dataset_id']!==$dataset_id||(int)$page['active_version_id']!==(int)$dataset['version']['active_version_id']||(int)$page['offset']!==$offset||(int)$page['row_count']!==min(100,$row_count-$offset)){throw new RuntimeException('Downloaded scoped backup page identity/checksum mismatch.');}$page_hashes[]=$page_response['page_sha256'];foreach($page['rows'] as $row){if((int)$row['row_index']!==$seen||!hash_equals(strtolower((string)$row['row_sha256']),hash('sha256',(string)$row['row_data']))){throw new RuntimeException('Downloaded scoped backup row ordering/hash mismatch.');}hash_update($digest,$seen."\0".$row['url_path']."\0".$row['row_sha256']."\n");$seen++;}$this->write_exact($handle,V4MPG_Table_Deploy_Service::canonical_json(array('record'=>'page','page_sha256'=>$page_response['page_sha256'],'page'=>$page))."\n");}
					$ordered=hash_final($digest);if($seen!==$row_count||!hash_equals($ordered,(string)$dataset['version']['dataset_sha256'])){throw new RuntimeException('Downloaded scoped backup dataset digest mismatch.');}$proofs[]=array('project_id'=>$project_id,'dataset_id'=>$dataset_id,'row_count'=>$seen,'ordered_digest'=>$ordered,'pages_sha256'=>V4MPG_Table_Deploy_Service::sha256($page_hashes));
				}
				if(!fflush($handle)){throw new RuntimeException('Unable to flush local scoped backup.');}if(function_exists('fsync')&&!fsync($handle)){throw new RuntimeException('Unable to fsync local scoped backup.');}fclose($handle);$handle=null;
				$size=filesize($partial);$sha=hash_file('sha256',$partial);if(false===$size||$size<1||!is_string($sha)){throw new RuntimeException('Unable to re-read local scoped backup.');}
				if(!rename($partial,$output)||!is_file($output)||!hash_equals($sha,hash_file('sha256',$output))){throw new RuntimeException('Atomic local scoped backup finalization failed.');}
				$reread_proofs=$this->verify_persisted_backup($output,$manifest,$open['backup_manifest_sha256']);if(V4MPG_Table_Deploy_Service::sha256($reread_proofs)!==V4MPG_Table_Deploy_Service::sha256($proofs)){throw new RuntimeException('Persisted scoped backup semantic re-read proof mismatch.');}$proofs=$reread_proofs;
				$sealed=self::$client->request('backup-seal',array('protocol'=>V4MPG_Table_Deploy_Service::PROTOCOL_VERSION,'operation_id'=>$request['operation_id'],'expected_site'=>$request['expected_site'],'backup_token'=>$open['backup_token'],'local_backup_sha256'=>$sha,'datasets'=>$proofs));$sealed_ok=true;
				if(!hash_equals($sha,(string)($sealed['backup_sha256']??''))||false!==($sealed['remote_artifact_retained']??true)){throw new RuntimeException('Remote scoped backup seal failed.');}
				$receipt=array('receipt_version'=>1,'status'=>'verified-local-scoped-backup','created_at'=>gmdate('c'),'path'=>$output,'bytes'=>$size,'sha256'=>$sha,'manifest_sha256'=>$open['backup_manifest_sha256'],'backup_token'=>$sealed['backup_token'],'operation_id'=>$request['operation_id'],'expected_site'=>$request['expected_site'],'datasets'=>$proofs,'remote_artifact_retained'=>false);
				$receipt_path=$output.'.receipt.json';$this->write_atomic_json($receipt_path,$receipt);\WP_CLI::log(wp_json_encode(array_merge($receipt,array('receipt_path'=>$receipt_path)),JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE));
			}catch(\Throwable $error){if(is_resource($handle)){fclose($handle);}@unlink($partial);if(!$sealed_ok&&is_array($open)&&isset($open['backup_token'])){try{self::$client->request('backup-abort',array('protocol'=>V4MPG_Table_Deploy_Service::PROTOCOL_VERSION,'operation_id'=>$request['operation_id'],'expected_site'=>$request['expected_site'],'backup_token'=>$open['backup_token'],'reason'=>'local-backup-failed'));}catch(\Throwable $abort_error){throw new RuntimeException($error->getMessage().' | Remote scoped-backup abort failed: '.$abort_error->getMessage(),0,$error);}}throw $error;}
		}

		/** Deploy an exact release using a fresh verified local backup receipt. */
		public function deploy( $args, $assoc ) {
			unset($args);
			if(empty($assoc['site-id'])){throw new RuntimeException('Deploy requires --site-id for durable local evidence.');}
			$output=$this->absolute_output($assoc,'output-receipt');
			$this->preflight_new_output($output);
			$request=$this->read_json_arg($assoc,'request');$receipt=$this->read_json_arg($assoc,'backup-receipt');
			$this->assert_no_unresolved_remote_cleanup();
			$fresh=strtotime((string)($receipt['created_at']??''));if('verified-local-scoped-backup'!==($receipt['status']??'')||!is_file($receipt['path'])||!hash_equals((string)$receipt['sha256'],hash_file('sha256',$receipt['path']))||!hash_equals((string)$receipt['operation_id'],(string)$request['operation_id'])||V4MPG_Table_Deploy_Service::sha256($receipt['expected_site']??array())!==V4MPG_Table_Deploy_Service::sha256($request['expected_site']??array())||false===$fresh||time()-$fresh>V4MPG_Table_Deploy_Service::BACKUP_TTL){throw new RuntimeException('Fresh local scoped backup receipt verification failed before deploy.');}
			$this->verify_backup_artifact_from_receipt($receipt);
			$proof_ids=array();foreach($receipt['datasets'] as $proof){$proof_ids[(string)$proof['dataset_id']]=(int)$proof['project_id'];}foreach(($request['deployment']['targets']??array()) as $target){if(($proof_ids[(string)$target['dataset_id']]??0)!==(int)$target['project_id']){throw new RuntimeException('Local scoped backup receipt does not cover every deployment target.');}}
			$request['backup_token']=$receipt['backup_token'];$request['backup_sha256']=$receipt['sha256'];$request['payload_sha256']=V4MPG_Table_Deploy_Service::sha256($request['deployment']);
			$pending=$output.'.pending.json';
			$this->write_atomic_json($pending,array('receipt_type'=>'agsync-v4mpg-live-deployment-pending','schema_version'=>1,'status'=>'pending-remote-result','created_at'=>gmdate('c'),'site_id'=>(string)$assoc['site-id'],'operation_id'=>(string)($request['operation_id']??''),'request_sha256'=>V4MPG_Table_Deploy_Service::sha256($request),'output_path'=>$output));
			$result=self::$client->request('deploy',$request);V4MPG_Table_Deploy_Service::assert_deploy_response_binding($result,$request,$receipt);
			$composite=array('receipt_type'=>'agsync-v4mpg-live-deployment','schema_version'=>1,'phase'=>(string)($assoc['phase']??'deploy'),'site_id'=>(string)$assoc['site-id'],'release_id'=>(string)$result['release']['release_id'],'candidate_summary_sha256'=>(string)$result['release']['candidate_summary_sha256'],'created_at'=>gmdate('c'),'backup_receipt'=>array('path'=>wp_normalize_path((string)$assoc['backup-receipt']),'sha256'=>hash_file('sha256',$assoc['backup-receipt']),'artifact_path'=>$receipt['path'],'artifact_sha256'=>$receipt['sha256'],'remote_artifact_retained'=>false),'deploy_receipt'=>$result,'deploy_receipt_sha256'=>V4MPG_Table_Deploy_Service::sha256($result));
			$this->write_atomic_json($output,$composite);
			if(!unlink($pending)){throw new RuntimeException('Deployment completed and receipt was persisted, but the pending journal could not be removed.');}
			\WP_CLI::log(wp_json_encode(array_merge($composite,array('receipt_path'=>$output,'receipt_sha256'=>hash_file('sha256',$output))),JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE));
		}

		public function verify( $args, $assoc ) { $this->simple( 'verify', $assoc ); }
		public function status( $args, $assoc ) { $this->simple( 'status', $assoc ); }
		public function rollback( $args, $assoc ) {
			unset($args);$output=$this->absolute_output($assoc,'output-receipt');$this->preflight_new_output($output);$request=$this->read_json_arg($assoc,'request');$pending=$output.'.pending.json';
			$this->write_atomic_json($pending,array('receipt_type'=>'agsync-v4mpg-live-rollback-pending','schema_version'=>1,'status'=>'pending-remote-result','created_at'=>gmdate('c'),'operation_id'=>(string)($request['operation_id']??''),'request_sha256'=>V4MPG_Table_Deploy_Service::sha256($request),'output_path'=>$output));
			$result=self::$client->request('rollback',$request);$composite=array('receipt_type'=>'agsync-v4mpg-live-rollback','schema_version'=>1,'created_at'=>gmdate('c'),'rollback_receipt'=>$result,'rollback_receipt_sha256'=>V4MPG_Table_Deploy_Service::sha256($result));$this->write_atomic_json($output,$composite);if(!unlink($pending)){throw new RuntimeException('Rollback completed and receipt was persisted, but the pending journal could not be removed.');}\WP_CLI::log(wp_json_encode($composite,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE));
		}

		public function recover( $args, $assoc ) {
			unset($args);$output=$this->absolute_output($assoc,'output-receipt');$this->preflight_new_output($output);$request=$this->read_json_arg($assoc,'request');$pending=$output.'.pending.json';
			$this->write_atomic_json($pending,array('receipt_type'=>'agsync-v4mpg-live-recovery-pending','schema_version'=>1,'status'=>'pending-remote-result','created_at'=>gmdate('c'),'operation_id'=>(string)($request['operation_id']??''),'request_sha256'=>V4MPG_Table_Deploy_Service::sha256($request),'output_path'=>$output));
			$result=self::$client->request('recover',$request);$composite=array('receipt_type'=>'agsync-v4mpg-live-recovery','schema_version'=>1,'created_at'=>gmdate('c'),'recovery_receipt'=>$result,'recovery_receipt_sha256'=>V4MPG_Table_Deploy_Service::sha256($result));$this->write_atomic_json($output,$composite);if(!unlink($pending)){throw new RuntimeException('Recovery completed and receipt was persisted, but the pending journal could not be removed.');}\WP_CLI::log(wp_json_encode($composite,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE));
		}

		/** Create a fresh full live snapshot, verify it locally, then delete only that remote package. */
		public function full_backup_local( $args, $assoc ) {
			unset($args);$output=$this->absolute_output($assoc,'output');$partial=$output.'.partial';$receipt_path=$output.'.receipt.json';$pending=$output.'.pending.json';$operation_pending=$output.'.operation-pending.json';$remote_pending=$output.'.remote-pending.json';
			$this->preflight_new_output($output);$this->preflight_new_output($receipt_path);if(file_exists($operation_pending)||file_exists($remote_pending)){throw new RuntimeException('A prior remote full-backup journal already exists and requires reconciliation.');}
			$this->write_atomic_json($pending,array('receipt_type'=>'agsync-full-live-backup-pending','schema_version'=>1,'status'=>'creating-remote-snapshot','created_at'=>gmdate('c'),'remote_host'=>strtolower((string)wp_parse_url(self::$config->get_remote_url(),PHP_URL_HOST)),'output_path'=>$output));
			$operation_id='';$basename='';$sha='';$bytes=0;$manifest=array();$manifest_id='';$manifest_sha='';$cleanup=null;$primary_error=null;$cleanup_error=null;
			try{
				$snapshot=self::$http->create_remote_snapshot('live-download-only-snapshot',null,function($id)use(&$operation_id,$operation_pending,$output){$operation_id=(string)$id;$this->write_atomic_json($operation_pending,array('receipt_type'=>'agsync-full-live-backup-operation','schema_version'=>1,'status'=>'remote-operation-started','created_at'=>gmdate('c'),'operation_id'=>$operation_id,'remote_host'=>strtolower((string)wp_parse_url(self::$config->get_remote_url(),PHP_URL_HOST)),'output_path'=>$output));});if(is_wp_error($snapshot)){throw new RuntimeException($snapshot->get_error_message());}
				$basename=(string)($snapshot['basename']??'');$sha=strtolower((string)($snapshot['sha256']??''));$bytes=(int)($snapshot['size_bytes']??0);$manifest=is_array($snapshot['manifest']??null)?$snapshot['manifest']:array();$manifest_id=(string)($manifest['id']??'');$manifest_sha=V4MPG_Table_Deploy_Service::sha256($manifest);$snapshot_scope=(string)($snapshot['snapshot_scope']??($manifest['snapshot_scope']??''));
				if(''===$operation_id||''===$basename||!preg_match('/^[a-f0-9]{64}$/',$sha)||$bytes<1||'full'!==$snapshot_scope||''===$manifest_id||'full'!==($manifest['snapshot_scope']??'')){throw new RuntimeException('Fresh remote full snapshot metadata is incomplete.');}
				$this->write_atomic_json($remote_pending,array('receipt_type'=>'agsync-full-live-backup-remote-artifact','schema_version'=>1,'status'=>'remote-cleanup-required','created_at'=>gmdate('c'),'operation_id'=>$operation_id,'remote_host'=>strtolower((string)wp_parse_url(self::$config->get_remote_url(),PHP_URL_HOST)),'basename'=>$basename,'sha256'=>$sha,'manifest_id'=>$manifest_id,'manifest_sha256'=>$manifest_sha));
				$download=self::$http->download_snapshot($basename,$partial);if(is_wp_error($download)){throw new RuntimeException($download->get_error_message());}if(!is_file($partial)||(int)filesize($partial)!==$bytes||!hash_equals($sha,hash_file('sha256',$partial))){throw new RuntimeException('Downloaded full snapshot size/SHA mismatch.');}
				$validated=self::$importer->validate_package($partial,$sha);if(is_wp_error($validated)){throw new RuntimeException($validated->get_error_message());}$local_manifest=$validated['manifest']??array();$full=self::$file_system->validate_full_snapshot_package($partial);if(empty($full['ok'])||'full'!==($local_manifest['snapshot_scope']??'')||'remote'!==($local_manifest['source_role']??'')||strtolower((string)($local_manifest['source_host']??''))!==strtolower((string)wp_parse_url(self::$config->get_remote_url(),PHP_URL_HOST))||!hash_equals($manifest_id,(string)($local_manifest['id']??''))||!hash_equals($manifest_sha,V4MPG_Table_Deploy_Service::sha256($local_manifest))){throw new RuntimeException('Downloaded package failed full/source identity validation.');}
				$manifest=$local_manifest;if(!rename($partial,$output)||!is_file($output)||!hash_equals($sha,hash_file('sha256',$output))){throw new RuntimeException('Atomic full backup finalization failed.');}
			}catch(\Throwable $error){$primary_error=$error;
			}finally{
				if(is_file($partial)){@unlink($partial);}
				if(''!==$operation_id&&''!==$basename&&preg_match('/^[a-f0-9]{64}$/',$sha)&&''!==$manifest_id&&preg_match('/^[a-f0-9]{64}$/',$manifest_sha)){
					$cleanup=self::$http->delete_remote_snapshot_exact($operation_id,$basename,$sha,$manifest_id,$manifest_sha);
					if(is_wp_error($cleanup)||!is_array($cleanup)||!hash_equals($manifest_id,(string)($cleanup['manifest_id']??''))||false!==($cleanup['exists_after']??true)||false!==($cleanup['sidecar_exists_after']??true)){$cleanup_error=new RuntimeException(is_wp_error($cleanup)?$cleanup->get_error_message():'Exact remote snapshot cleanup was not verified.');}
				}elseif(''!==$operation_id){$cleanup_error=new RuntimeException('Exact remote snapshot cleanup proof was unavailable for the started operation.');}
			}
			if(null===$cleanup_error&&is_array($cleanup)&&false===($cleanup['exists_after']??true)){if(is_file($remote_pending)){@unlink($remote_pending);}if(is_file($operation_pending)){@unlink($operation_pending);}}
			if(null!==$primary_error||null!==$cleanup_error){$messages=array();if(null!==$primary_error){$messages[]=$primary_error->getMessage();}if(null!==$cleanup_error){$messages[]='REMOTE CLEANUP REQUIRED: '.$cleanup_error->getMessage();}throw new RuntimeException(implode(' | ',$messages));}
			$receipt=array('receipt_version'=>1,'status'=>'verified-local-full-live-backup','created_at'=>gmdate('c'),'path'=>$output,'bytes'=>$bytes,'sha256'=>$sha,'manifest_id'=>$manifest_id,'manifest_sha256'=>$manifest_sha,'source_home_url'=>(string)($manifest['source_home_url']??''),'source_host'=>(string)$manifest['source_host'],'source_role'=>'remote','snapshot_scope'=>'full','remote_cleanup'=>$cleanup);$this->write_atomic_json($receipt_path,$receipt);
			if((is_file($remote_pending)&&!unlink($remote_pending))||(is_file($operation_pending)&&!unlink($operation_pending))||!unlink($pending)){throw new RuntimeException('Full backup completed with verified remote cleanup, but a pending journal could not be removed.');}\WP_CLI::log(wp_json_encode($receipt,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE));
		}

		private function simple($action,$assoc){$result=$this->request_result($action,$assoc);\WP_CLI::log(wp_json_encode($result,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE));}
		private function request_result($action,$assoc){return self::$client->request($action,$this->read_json_arg($assoc,'request'));}
		private function read_json_arg($assoc,$key){if(empty($assoc[$key])||!is_file($assoc[$key])){throw new RuntimeException('--'.$key.' must point to a readable JSON file.');}$raw=file_get_contents($assoc[$key]);$data=json_decode((string)$raw,true);if(!is_array($data)){throw new RuntimeException('Invalid JSON file: '.$assoc[$key]);}return $data;}
		private function absolute_output($assoc,$key){if(empty($assoc[$key])){throw new RuntimeException('--'.$key.' is required.');}$path=wp_normalize_path((string)$assoc[$key]);if(!preg_match('#^(?:[A-Za-z]:[\\/]|/)#',$path)){throw new RuntimeException('--'.$key.' must be an absolute local path.');}$root=defined('AG_SYNC_BRIDGE_LOCAL_BACKUP_ROOT')?rtrim(wp_normalize_path((string)AG_SYNC_BRIDGE_LOCAL_BACKUP_ROOT),'/'):'';if(''===$root||0!==strpos(strtolower($path.'/'),strtolower($root.'/'))){throw new RuntimeException('Backup output is outside AG_SYNC_BRIDGE_LOCAL_BACKUP_ROOT.');}$forbidden=array(wp_normalize_path(ABSPATH),wp_normalize_path(AG_SYNC_BRIDGE_PLUGIN_DIR));foreach($forbidden as $base){if(0===strpos(strtolower($path.'/'),strtolower(rtrim($base,'/').'/'))){throw new RuntimeException('Backup output must be outside the web/plugin roots.');}}return $path;}
		private function write_exact($handle,$bytes){$length=strlen($bytes);$written=fwrite($handle,$bytes);if($written!==$length){throw new RuntimeException('Incomplete local backup write.');}}
		private function preflight_new_output($path){
			if(file_exists($path)||file_exists($path.'.partial')||file_exists($path.'.pending.json')){throw new RuntimeException('Local output or recovery journal already exists: '.$path);}$dir=dirname($path);if(!is_dir($dir)&&!wp_mkdir_p($dir)){throw new RuntimeException('Unable to create local output directory.');}$probe=$dir.'/.agsb-output-probe-'.wp_generate_uuid4();$handle=fopen($probe,'x+b');if(false===$handle){throw new RuntimeException('Unable to create local output preflight probe.');}try{$bytes="AGSB-PREFLIGHT\n";$this->write_exact($handle,$bytes);if(!fflush($handle)||(function_exists('fsync')&&!fsync($handle))){throw new RuntimeException('Unable to durably flush local output preflight probe.');}}finally{fclose($handle);}if(!hash_equals(hash('sha256',$bytes),hash_file('sha256',$probe))||!unlink($probe)||file_exists($probe)){throw new RuntimeException('Local output preflight verification/cleanup failed.');}
		}
		private function write_atomic_json($path,array $data){
			if(file_exists($path)){throw new RuntimeException('Refusing to overwrite an existing local receipt or journal: '.$path);}$dir=dirname($path);if(!is_dir($dir)&&!wp_mkdir_p($dir)){throw new RuntimeException('Unable to create local receipt directory.');}$tmp=$path.'.'.wp_generate_uuid4().'.partial';$handle=fopen($tmp,'x+b');if(false===$handle){throw new RuntimeException('Unable to create local receipt temporary file.');}try{$bytes=V4MPG_Table_Deploy_Service::canonical_json($data);$this->write_exact($handle,$bytes);if(!fflush($handle)||(function_exists('fsync')&&!fsync($handle))){throw new RuntimeException('Unable to durably flush local receipt.');}}finally{fclose($handle);}if(!rename($tmp,$path)||!is_file($path)||!hash_equals(hash('sha256',$bytes),hash_file('sha256',$path))){@unlink($tmp);throw new RuntimeException('Unable to write local backup receipt atomically.');}
		}
		private function verify_backup_artifact_from_receipt(array $receipt){
			if(!isset($receipt['path'],$receipt['manifest_sha256'],$receipt['datasets'])||!is_array($receipt['datasets'])){throw new RuntimeException('Scoped backup receipt semantic proof is incomplete.');}$handle=fopen((string)$receipt['path'],'rb');if(false===$handle){throw new RuntimeException('Unable to open scoped backup artifact for deploy preflight.');}try{$line=fgets($handle);}finally{fclose($handle);}if(false===$line){throw new RuntimeException('Scoped backup artifact has no manifest record.');}$record=json_decode(trim($line),true);$manifest=$record['manifest']??null;if(!is_array($record)||'manifest'!==($record['record']??'')||!is_array($manifest)||!hash_equals((string)$receipt['manifest_sha256'],(string)($record['manifest_sha256']??''))||!hash_equals((string)$receipt['manifest_sha256'],V4MPG_Table_Deploy_Service::sha256($manifest))){throw new RuntimeException('Scoped backup artifact manifest proof mismatch.');}$proofs=$this->verify_persisted_backup((string)$receipt['path'],$manifest,(string)$receipt['manifest_sha256']);if(!hash_equals(V4MPG_Table_Deploy_Service::sha256($receipt['datasets']),V4MPG_Table_Deploy_Service::sha256($proofs))){throw new RuntimeException('Scoped backup artifact semantic proof differs from its receipt.');}
		}
		private function assert_no_unresolved_remote_cleanup(){
			$root=defined('AG_SYNC_BRIDGE_LOCAL_BACKUP_ROOT')?rtrim(wp_normalize_path((string)AG_SYNC_BRIDGE_LOCAL_BACKUP_ROOT),'/'):'';if(''===$root||!is_dir($root)){return;}$remote_host=strtolower((string)wp_parse_url(self::$config->get_remote_url(),PHP_URL_HOST));$iterator=new \RecursiveIteratorIterator(new \RecursiveDirectoryIterator($root,\FilesystemIterator::SKIP_DOTS));foreach($iterator as $entry){if(!$entry->isFile()||!preg_match('/\.pending\.json$|-pending\.json$/',(string)$entry->getFilename())){continue;}$path=wp_normalize_path($entry->getPathname());$journal=json_decode((string)file_get_contents($path),true);$exact_name=1===preg_match('/\.(?:remote|operation)-pending\.json$/',(string)$entry->getFilename());if(!is_array($journal)){if($exact_name){throw new RuntimeException('Unreadable remote-cleanup journal blocks deployment: '.$path);}continue;}$receipt_type=(string)($journal['receipt_type']??'');if(!$exact_name&&0!==strpos($receipt_type,'agsync-full-live-backup-')){continue;}$journal_host=strtolower((string)($journal['remote_host']??''));if(''===$journal_host||''===$remote_host||hash_equals($remote_host,$journal_host)){throw new RuntimeException('Unresolved remote snapshot cleanup blocks deployment: '.$path);}}
		}
		private function verify_persisted_backup($path,array $manifest,$manifest_sha){$handle=fopen($path,'rb');if(false===$handle){throw new RuntimeException('Unable to re-open persisted scoped backup.');}$expected=array();foreach($manifest['datasets'] as $dataset){$expected[(string)$dataset['version']['dataset_id']]=$dataset;}$states=array();$line_number=0;try{while(false!==($line=fgets($handle))){$line_number++;$record=json_decode(trim($line),true);if(!is_array($record)){throw new RuntimeException('Persisted scoped backup contains invalid JSONL.');}if(1===$line_number){if('manifest'!==($record['record']??'')||!hash_equals($manifest_sha,(string)($record['manifest_sha256']??''))||V4MPG_Table_Deploy_Service::sha256($record['manifest']??array())!==V4MPG_Table_Deploy_Service::sha256($manifest)){throw new RuntimeException('Persisted scoped backup manifest mismatch.');}continue;}if('page'!==($record['record']??'')||!is_array($record['page']??null)||!hash_equals((string)$record['page_sha256'],V4MPG_Table_Deploy_Service::sha256($record['page']))){throw new RuntimeException('Persisted scoped backup page checksum mismatch.');}$page=$record['page'];$id=(string)$page['dataset_id'];if(!isset($expected[$id])){throw new RuntimeException('Persisted page is outside manifest datasets.');}$state=$states[$id]??array('project_id'=>(int)$expected[$id]['project']['project_id'],'dataset_id'=>$id,'row_count'=>0,'digest'=>hash_init('sha256'),'page_hashes'=>array());$offset=$state['row_count'];if((int)$page['project_id']!==$state['project_id']||(int)$page['active_version_id']!==(int)$expected[$id]['version']['active_version_id']||(int)$page['offset']!==$offset||(int)$page['row_count']!==count($page['rows'])){throw new RuntimeException('Persisted scoped backup page identity/order mismatch.');}foreach($page['rows'] as $row){if((int)$row['row_index']!==$state['row_count']||!hash_equals(strtolower((string)$row['row_sha256']),hash('sha256',(string)$row['row_data']))){throw new RuntimeException('Persisted scoped backup row proof mismatch.');}hash_update($state['digest'],$state['row_count']."\0".$row['url_path']."\0".$row['row_sha256']."\n");$state['row_count']++;}$state['page_hashes'][]=$record['page_sha256'];$states[$id]=$state;}}finally{fclose($handle);}if($line_number<2||count($states)!==count($expected)){throw new RuntimeException('Persisted scoped backup is incomplete.');}$proofs=array();foreach($manifest['datasets'] as $dataset){$id=(string)$dataset['version']['dataset_id'];$state=$states[$id];$digest=hash_final($state['digest']);if($state['row_count']!==(int)$dataset['version']['row_count']||!hash_equals($digest,(string)$dataset['version']['dataset_sha256'])){throw new RuntimeException('Persisted scoped backup dataset digest mismatch.');}$proofs[]=array('project_id'=>$state['project_id'],'dataset_id'=>$id,'row_count'=>$state['row_count'],'ordered_digest'=>$digest,'pages_sha256'=>V4MPG_Table_Deploy_Service::sha256($state['page_hashes']));}return $proofs;}
	}
}
